version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
    postgres-data-dev: