version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  bot:
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
        - .env

volumes:
    postgres-data: